# -*- coding: utf-8 -*-
"""customer_churn_prod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eU9Zm8oh8oNupGyAOF085hcoxEAh_JjH
"""

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score
)
from sklearn.feature_selection import SelectKBest, chi2, f_classif , VarianceThreshold, mutual_info_classif

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "blastchar/telco-customer-churn",
"WA_Fn-UseC_-Telco-Customer-Churn.csv",

)
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan).astype(float)
# df = df.drop('TotalCharges', axis=1)
df['SeniorCitizen'] = df['SeniorCitizen'].astype('object')

x = df.drop(['Churn','customerID'],axis = 1)
y = df['Churn']
y = (y == 'Yes').astype(int)  # Convert 'Yes'/'No' to 1/0 , trees expect the numeric targets

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3 , random_state=0)
num_cols = ['tenure', 'MonthlyCharges','TotalCharges'] # removing TotalCharges affect the model accuracy

cat_cols = ['gender',	'SeniorCitizen'	,'Partner',	'Dependents'	,'PhoneService','MultipleLines','InternetService',	'OnlineSecurity'	,'OnlineBackup'	,'DeviceProtection',	'TechSupport'	,'StreamingTV'	,'StreamingMovies'	,'Contract'	,'PaperlessBilling'	,'PaymentMethod']

num_preprocess = Pipeline([
   ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

cat_preprocess = Pipeline([
   ('imputer', SimpleImputer(strategy='most_frequent')),
   ('encoder', OneHotEncoder(handle_unknown='ignore', drop='first'))
])

preprocessor = ColumnTransformer([
    ('num', num_preprocess, num_cols),
    ('cat', cat_preprocess, cat_cols)
])

corr = x[num_cols].corr()


pipeline = Pipeline([
    ('preprocess', preprocessor),
    ('classifier',   RandomForestClassifier(class_weight ='balanced',
                                            max_depth =7,
                                            min_samples_split= 5,
                                            n_estimators =50,
                                            random_state=42,
                                            n_jobs=-1))
])
pipeline.fit(x_train, y_train)
y_pred = pipeline.predict(x_test)
y_proba = pipeline.predict_proba(x_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_proba))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

import joblib

# Saving the pipeline
joblib.dump(pipeline, 'customer_churn_model.pkl')
print("Pipeline saved as customer_churn_model.pkl")
x_test_manual = pd.DataFrame([
    {
        'gender': 'Female',
        'SeniorCitizen': 0,
        'Partner': 'Yes',
        'Dependents': 'No',
        'tenure': 5,
        'PhoneService': 'Yes',
        'MultipleLines': 'No',
        'InternetService': 'Fiber optic',
        'OnlineSecurity': 'No',
        'OnlineBackup': 'Yes',
        'DeviceProtection': 'No',
        'TechSupport': 'No',
        'StreamingTV': 'No',
        'StreamingMovies': 'No',
        'Contract': 'Month-to-month',
        'PaperlessBilling': 'Yes',
        'PaymentMethod': 'Electronic check',
        'MonthlyCharges': 70.35,
        'TotalCharges': 350.5
    },
    {
        'gender': 'Male',
        'SeniorCitizen': 1,
        'Partner': 'No',
        'Dependents': 'No',
        'tenure': 50,
        'PhoneService': 'Yes',
        'MultipleLines': 'Yes',
        'InternetService': 'DSL',
        'OnlineSecurity': 'Yes',
        'OnlineBackup': 'No',
        'DeviceProtection': 'Yes',
        'TechSupport': 'Yes',
        'StreamingTV': 'Yes',
        'StreamingMovies': 'Yes',
        'Contract': 'Two year',
        'PaperlessBilling': 'No',
        'PaymentMethod': 'Mailed check',
        'MonthlyCharges': 99.9,
        'TotalCharges': 5000.0
    }
])

# Make predictions
y_pred_manual = pipeline.predict(x_test_manual)
y_proba_manual = pipeline.predict_proba(x_test_manual)[:,1]

print("Predicted classes:", y_pred_manual)
print("Predicted probabilities:", y_proba_manual)

